Models
ctcuff/CAP4720-final-project pull request #9
Opened 2021-11-20 01:52 UTC by TravisMWise

2021-11-20 05:06 UTC, Armintron requested changes

2021-11-20 05:06 UTC, Armintron commented on src/index.js
> +  myAsteroid1.physics.angularVelocity = new Vector3(0, 30, 0);
Nit-pick: this should happen before you add the object to the gamemanager

2021-11-20 05:06 UTC, Armintron commented on src/index.js
> +  // manager.addObjects([ufo]);
Commented code can be deleted

2021-11-20 05:06 UTC, Armintron commented on src/index.js
> +  manager.addObjects([myAsteroid1]);
Use `addObject` function

2021-11-20 05:06 UTC, Armintron commented on src/index.js
> +  const raymanModelExtents = manager.modelList[3].getModelExtent();
Rename variable since it's no longer Rayman extents

2021-11-20 18:08 UTC, ctcuff commented
Overall looks good but I'd like to possibly wait on #10 to be addressed first. Having to access models from the manager via index will get cumbersome when we have multiple models to reference

2021-11-22 03:31 UTC, Armintron approved these changes

2021-11-22 03:51 UTC, Armintron commented
> Overall looks good but I'd like to possibly wait on #10 to be addressed first. Having to access models from the manager via index will get cumbersome when we have multiple models to reference

This has been changed

2021-11-22 14:12 UTC, merged